BINANCE_API_KEY = 'binance_api_key'
BINANCE_SECRET_KEY = 'binance_secret_key'

TELEGRAM_BOT_TOKEN = ""
TELEGRAM_BOT_CHAT_ID = ""

MAX_PERCENTAGE_TO_RISK = 2
MAX_VS_CURRENCY_TO_USE = 13

FILE_NAME_TO_CLOSE_BOT = "close_bot"
